# Ejemplos

POST https://api-mongodb-dev-epqh.1.us-1.fl0.io/api/users HTTP/1.1
content-type: application/json

{ 
    "nombre": "Eva", 
    "edad": 20 
}

### 

POST https://api-mongodb-dev-epqh.1.us-1.fl0.io/api/users HTTP/1.1
content-type: application/json

{ 
    "nombre": "Jose", 
    "edad": 21 
}


### 

GET https://api-mongodb-dev-epqh.1.us-1.fl0.io/api/users HTTP/1.1
content-type: application/json

###

GET https://api-mongodb-dev-epqh.1.us-1.fl0.io/api/users HTTP/1.1
content-type: application/json

###

PUT https://api-mongodb-dev-epqh.1.us-1.fl0.io/api/users HTTP/1.1
content-type: application/json

{ 
    "nombre": "José Antonio", 
    "edad": 32 
}

###

DELETE https://api-mongodb-dev-epqh.1.us-1.fl0.io/api/usersHTTP/1.1
content-type: application/json

###

DELETE https://api-mongodb-dev-nnas.3.us-1.fl0.io/api/users/6542da20c20d9ad95c739701 HTTP/1.1
content-type: application/json


### 

POST https://api-mongodb-dev-epqh.1.us-1.fl0.io/api/users HTTP/1.1
content-type: application/json

{ 
    "nombre": "Angel", 
    "edad": 21 
}


### 

POST https://api-mongodb-dev-epqh.1.us-1.fl0.io/api/users HTTP/1.1
content-type: application/json

{ 
    "nombre": "Javi", 
    "edad": 20
}

### 

POST https://api-mongodb-dev-epqh.1.us-1.fl0.io/api/users HTTP/1.1
content-type: application/json

{ 
    "nombre": "Antonio", 
    "edad": 26
}
