# Ejemplos

POST https://api-mongodb-dev-epqh.1.us-1.fl0.io/api/users HTTP/1.1
content-type: application/json

{ 
    "nombre": "Eva", 
    "edad": 20 
}

### 

POST https://api-mongodb-dev-epqh.1.us-1.fl0.io/api/users HTTP/1.1
content-type: application/json

{ 
    "nombre": "Jose", 
    "edad": 21 
}


### 

GET https://api-mongodb-dev-epqh.1.us-1.fl0.io/api/users HTTP/1.1
content-type: application/json

###

GET https://api-mongodb-dev-epqh.1.us-1.fl0.io/api/users HTTP/1.1
content-type: application/json

###

PUT https://api-mongodb-dev-epqh.1.us-1.fl0.io/api/users HTTP/1.1
content-type: application/json

{ 
    "nombre": "José Antonio", 
    "edad": 32 
}

###



POST https://api-mongodb-dev-epqh.1.us-1.fl0.io/api/users HTTP/1.1
content-type: application/json

{ 
    "nombre": "Angel", 
    "edad": 21 
}


### 

POST https://api-mongodb-dev-epqh.1.us-1.fl0.io/api/users HTTP/1.1
content-type: application/json

{ 
    "nombre": "Javi", 
    "edad": 20
}

### 

POST https://api-mongodb-dev-epqh.1.us-1.fl0.io/api/users HTTP/1.1
content-type: application/json

{ 
    "nombre": "Antonio", 
    "edad": 26
}

### actualizar un archivo
POST https://api-mongodb-dev-epqh.1.us-1.fl0.io/api/productos HTTP/1.1
Content-Type: application/json

{
    "id": "6",
    "nombre": "Nuevo Producto",
    "precio": 30
}

### actualizar un archivo

PUT https://api-mongodb-dev-epqh.1.us-1.fl0.io/api/users HTTP/1.1
Content-Type: application/json

{
    "id": ,
    "nombre": "mojon",
    "precio": 200
}


### eliminar un archivo
DELETE https://api-mongodb-dev-epqh.1.us-1.fl0.io/api/users HTTP/1.1
Content-Type: application/json
{ "id": "654cfaae3b9fb2b3aa8b5f3e" }